export type PartOfSpeech = 'noun' | 'adjective' | 'verb' | 'pronoun' | 'adverb' | 'number' | 'practice';

export interface WordItem {
    kana: string;
    romaji: string;
    translation: {
        en: string;
        it: string;
    };
    partOfSpeech: PartOfSpeech;
    type: 'Hiragana' | 'Katakana';
}

export const wordlist: WordItem[] = [
    // --- HIRAGANA WORDS ---
    { kana: "あおい", romaji: "aoi", translation: { en: "blue", it: "blu, azzurro" }, partOfSpeech: "adjective", type: "Hiragana" },
    { kana: "あかい", romaji: "akai", translation: { en: "red", it: "rosso" }, partOfSpeech: "adjective", type: "Hiragana" },
    { kana: "あさ", romaji: "asa", translation: { en: "morning", it: "mattina" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "あした", romaji: "ashita", translation: { en: "tomorrow", it: "domani" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "あし", romaji: "ashi", translation: { en: "foot, leg", it: "piede, gamba" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "あたま", romaji: "atama", translation: { en: "head", it: "testa" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "あなた", romaji: "anata", translation: { en: "you", it: "tu" }, partOfSpeech: "pronoun", type: "Hiragana" },
    { kana: "あね", romaji: "ane", translation: { en: "older sister", it: "sorella maggiore" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "あに", romaji: "ani", translation: { en: "older brother", it: "fratello maggiore" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "あめ", romaji: "ame", translation: { en: "rain", it: "pioggia" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "いえ", romaji: "ie", translation: { en: "house, home", it: "casa" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "いぬ", romaji: "inu", translation: { en: "dog", it: "cane" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "いけ", romaji: "ike", translation: { en: "pond", it: "stagno" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "いと", romaji: "ito", translation: { en: "thread", it: "filo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "うた", romaji: "uta", translation: { en: "song", it: "canzone" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "うみ", romaji: "umi", translation: { en: "sea, ocean", it: "mare" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "うわさ", romaji: "uwasa", translation: { en: "rumor", it: "pettegolezzo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "おとこ", romaji: "otoko", translation: { en: "man", it: "uomo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "おんな", romaji: "onna", translation: { en: "woman", it: "donna" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "おそい", romaji: "osoi", translation: { en: "slow, late", it: "lento, tardi" }, partOfSpeech: "adjective", type: "Hiragana" },
    { kana: "おいしい", romaji: "oishii", translation: { en: "delicious", it: "delizioso" }, partOfSpeech: "adjective", type: "Hiragana" },
    { kana: "おかね", romaji: "okane", translation: { en: "money", it: "soldi, denaro" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "おと", romaji: "oto", translation: { en: "sound, noise", it: "suono, rumore" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "かね", romaji: "kane", translation: { en: "money", it: "soldi, denaro" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "かみ", romaji: "kami", translation: { en: "paper, hair", it: "carta, capelli" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "かお", romaji: "kao", translation: { en: "face", it: "viso, faccia" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "かた", romaji: "kata", translation: { en: "shoulder", it: "spalla" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "からい", romaji: "karai", translation: { en: "spicy", it: "piccante" }, partOfSpeech: "adjective", type: "Hiragana" },
    { kana: "かわ", romaji: "kawa", translation: { en: "river", it: "fiume" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "きく", romaji: "kiku", translation: { en: "to listen, hear", it: "ascoltare" }, partOfSpeech: "verb", type: "Hiragana" },
    { kana: "きた", romaji: "kita", translation: { en: "north", it: "nord" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "きもの", romaji: "kimono", translation: { en: "kimono", it: "kimono" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "くも", romaji: "kumo", translation: { en: "cloud, spider", it: "nuvola, ragno" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "くるま", romaji: "kuruma", translation: { en: "car, vehicle", it: "macchina, auto" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "くすり", romaji: "kusuri", translation: { en: "medicine", it: "medicina" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "くつ", romaji: "kutsu", translation: { en: "shoes", it: "scarpe" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "くち", romaji: "kuchi", translation: { en: "mouth", it: "bocca" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "こえ", romaji: "koe", translation: { en: "voice", it: "voce" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ここ", romaji: "koko", translation: { en: "here", it: "qui" }, partOfSpeech: "pronoun", type: "Hiragana" },
    { kana: "こころ", romaji: "kokoro", translation: { en: "heart", it: "cuore" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "こと", romaji: "koto", translation: { en: "thing, matter", it: "cosa, fatto" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "さくら", romaji: "sakura", translation: { en: "cherry blossom", it: "fiore di ciliegio" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "さけ", romaji: "sake", translation: { en: "sake, alcohol", it: "sake, alcol" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "さkana", romaji: "sakana", translation: { en: "fish", it: "pesce" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "さかな", romaji: "sakana", translation: { en: "fish", it: "pesce" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "さる", romaji: "saru", translation: { en: "monkey", it: "scimmia" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "しお", romaji: "shio", translation: { en: "salt", it: "sale" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "しか", romaji: "shika", translation: { en: "deer", it: "cervo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "した", romaji: "shita", translation: { en: "tongue, under", it: "lingua, sotto" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "しろい", romaji: "shiroi", translation: { en: "white", it: "bianco" }, partOfSpeech: "adjective", type: "Hiragana" },
    { kana: "すし", romaji: "sushi", translation: { en: "sushi", it: "sushi" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "すいか", romaji: "suika", translation: { en: "watermelon", it: "anguria" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "すこし", romaji: "sukoshi", translation: { en: "a little", it: "un po'" }, partOfSpeech: "adverb", type: "Hiragana" },
    { kana: "せかい", romaji: "sekai", translation: { en: "world", it: "mondo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "そこ", romaji: "soko", translation: { en: "there", it: "lì" }, partOfSpeech: "pronoun", type: "Hiragana" },
    { kana: "そら", romaji: "sora", translation: { en: "sky", it: "cielo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "そと", romaji: "soto", translation: { en: "outside", it: "fuori" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "たこ", romaji: "tako", translation: { en: "octopus", it: "polpo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "たかい", romaji: "takai", translation: { en: "high, expensive", it: "alto, costoso" }, partOfSpeech: "adjective", type: "Hiragana" },
    { kana: "つくえ", romaji: "tsukue", translation: { en: "desk", it: "scrivania" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "つち", romaji: "tsuchi", translation: { en: "soil, earth", it: "terra, suolo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "て", romaji: "te", translation: { en: "hand", it: "mano" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "てんき", romaji: "tenki", translation: { en: "weather", it: "tempo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "とら", romaji: "tora", translation: { en: "tiger", it: "tigre" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "とり", romaji: "tori", translation: { en: "bird", it: "uccello" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "とけい", romaji: "tokei", translation: { en: "clock, watch", it: "orologio" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "なつ", romaji: "natsu", translation: { en: "summer", it: "estate" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "なまえ", romaji: "namae", translation: { en: "name", it: "nome" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "なみ", romaji: "nami", translation: { en: "wave", it: "onda" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "にし", romaji: "nishi", translation: { en: "west", it: "ovest" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "にく", romaji: "niku", translation: { en: "meat", it: "carne" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ねこ", romaji: "neko", translation: { en: "cat", it: "gatto" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "のり", romaji: "nori", translation: { en: "seaweed, glue", it: "alga nori, colla" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "のむ", romaji: "nomu", translation: { en: "to drink", it: "bere" }, partOfSpeech: "verb", type: "Hiragana" },
    { kana: "はこ", romaji: "hako", translation: { en: "box", it: "scatola" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "はな", romaji: "hana", translation: { en: "flower, nose", it: "fiore, naso" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "はし", romaji: "hashi", translation: { en: "chopsticks, bridge", it: "bacchette, ponte" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "はる", romaji: "haru", translation: { en: "spring", it: "primavera" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ひと", romaji: "hito", translation: { en: "person", it: "persona" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ひかり", romaji: "hikari", translation: { en: "light", it: "luce" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ひこうき", romaji: "hikouki", translation: { en: "airplane", it: "aereo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ふね", romaji: "fune", translation: { en: "ship, boat", it: "nave, barca" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ふゆ", romaji: "fuyu", translation: { en: "winter", it: "inverno" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "へや", romaji: "heya", translation: { en: "room", it: "stanza" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ほし", romaji: "hoshi", translation: { en: "star", it: "stella" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ほね", romaji: "hone", translation: { en: "bone", it: "osso" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "まち", romaji: "machi", translation: { en: "town, city", it: "città, paese" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "まつ", romaji: "matsu", translation: { en: "pine tree, to wait", it: "pino, aspettare" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "みみ", romaji: "mimi", translation: { en: "ear", it: "orecchio" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "みち", romaji: "michi", translation: { en: "road, path", it: "strada" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "むし", romaji: "mushi", translation: { en: "insect", it: "insetto" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "むne", romaji: "mune", translation: { en: "chest", it: "petto" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "むね", romaji: "mune", translation: { en: "chest", it: "petto" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "め", romaji: "me", translation: { en: "eye", it: "occhio" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "もの", romaji: "mono", translation: { en: "thing", it: "cosa" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "もり", romaji: "mori", translation: { en: "forest", it: "foresta" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "やま", romaji: "yama", translation: { en: "mountain", it: "montagna" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ゆき", romaji: "yuki", translation: { en: "snow", it: "neve" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ゆめ", romaji: "yume", translation: { en: "dream", it: "sogno" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "よる", romaji: "yoru", translation: { en: "night", it: "notte" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "よむ", romaji: "yomu", translation: { en: "to read", it: "leggere" }, partOfSpeech: "verb", type: "Hiragana" },
    { kana: "らく", romaji: "raku", translation: { en: "easy, comfortable", it: "comodo, facile" }, partOfSpeech: "adjective", type: "Hiragana" },
    { kana: "りす", romaji: "risu", translation: { en: "squirrel", it: "scoiattolo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "れい", romaji: "rei", translation: { en: "zero, bow", it: "zero, inchino" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ろく", romaji: "roku", translation: { en: "six", it: "sei" }, partOfSpeech: "number", type: "Hiragana" },
    { kana: "わたし", romaji: "watashi", translation: { en: "I, me", it: "io, me" }, partOfSpeech: "pronoun", type: "Hiragana" },
    { kana: "わに", romaji: "wani", translation: { en: "crocodile", it: "coccodrillo" }, partOfSpeech: "noun", type: "Hiragana" },

    // --- KATAKANA WORDS ---
    { kana: "カメラ", romaji: "kamera", translation: { en: "camera", it: "fotocamera" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "アメリカ", romaji: "amerika", translation: { en: "America", it: "America" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "サクラ", romaji: "sakura", translation: { en: "cherry blossom", it: "fiore di ciliegio" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "イカ", romaji: "ika", translation: { en: "squid", it: "seppia, calamaro" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "マイク", romaji: "maiku", translation: { en: "microphone", it: "microfono" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "テスト", romaji: "tesuto", translation: { en: "test, exam", it: "test, verifica" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "トイレ", romaji: "toire", translation: { en: "toilet, restroom", it: "bagno, gabinetto" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ココア", romaji: "kokoa", translation: { en: "cocoa", it: "cacao" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ナイフ", romaji: "naifu", translation: { en: "knife", it: "coltello" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "クラス", romaji: "kurasu", translation: { en: "class, classroom", it: "classe" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "テキスト", romaji: "tekisuto", translation: { en: "textbook", it: "libro di testo, testo" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ホテル", romaji: "hoteru", translation: { en: "hotel", it: "hotel, albergo" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ヘリ", romaji: "heri", translation: { en: "helicopter", it: "elicottero" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ヒント", romaji: "hinto", translation: { en: "hint, clue", it: "indizio, suggerimento" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "インク", romaji: "inku", translation: { en: "ink", it: "inchiostro" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ミント", romaji: "minto", translation: { en: "mint", it: "menta" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ハサミ", romaji: "hasami", translation: { en: "scissors", it: "forbici" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "メモ", romaji: "memo", translation: { en: "memo, note", it: "promemoria" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ネクタイ", romaji: "nekutai", translation: { en: "necktie", it: "cravatta" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "アニメ", romaji: "anime", translation: { en: "anime", it: "anime, cartone animato" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "スマホ", romaji: "sumaho", translation: { en: "smartphone", it: "smartphone" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "オアシス", romaji: "oashisu", translation: { en: "oasis", it: "oasi" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ロシア", romaji: "roshia", translation: { en: "Russia", it: "Russia" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "イタリア", romaji: "itaria", translation: { en: "Italy", it: "Italia" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ライフ", romaji: "raifu", translation: { en: "life", it: "vita" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ヘヤ", romaji: "heya", translation: { en: "room", it: "stanza" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ウニ", romaji: "uni", translation: { en: "sea urchin", it: "riccio di mare" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "コメ", romaji: "kome", translation: { en: "rice", it: "riso" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ライス", romaji: "raisu", translation: { en: "rice", it: "riso" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ラム", romaji: "ramu", translation: { en: "lamb, rum", it: "agnello, rum" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "フランス", romaji: "furansu", translation: { en: "France", it: "Francia" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "アフリカ", romaji: "afurika", translation: { en: "Africa", it: "Africa" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "イラク", romaji: "iraku", translation: { en: "Iraq", it: "Iraq" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ヘキサ", romaji: "hekisa", translation: { en: "hex", it: "esa" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "キロ", romaji: "kiro", translation: { en: "kilo", it: "chilo" }, partOfSpeech: "noun", type: "Katakana" }
];
