export type PartOfSpeech = 'noun' | 'adjective' | 'verb' | 'pronoun' | 'adverb' | 'number' | 'practice';

export interface WordItem {
    kana: string;
    kanji?: string; // Aggiunto come opzionale!
    romaji: string;
    translation: {
        en: string;
        it: string;
    };
    partOfSpeech: PartOfSpeech;
    type: 'Hiragana' | 'Katakana';
}

export const wordlist: WordItem[] = [
    // --- HIRAGANA WORDS ---
    { kana: "あおい", kanji: "青い", romaji: "aoi", translation: { en: "blue", it: "blu, azzurro" }, partOfSpeech: "adjective", type: "Hiragana" },
    { kana: "あかい", kanji: "赤い", romaji: "akai", translation: { en: "red", it: "rosso" }, partOfSpeech: "adjective", type: "Hiragana" },
    { kana: "あさ", kanji: "朝", romaji: "asa", translation: { en: "morning", it: "mattina" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "あした", kanji: "明日", romaji: "ashita", translation: { en: "tomorrow", it: "domani" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "あし", kanji: "足", romaji: "ashi", translation: { en: "foot, leg", it: "piede, gamba" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "あたま", kanji: "頭", romaji: "atama", translation: { en: "head", it: "testa" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "あなた", romaji: "anata", translation: { en: "you", it: "tu" }, partOfSpeech: "pronoun", type: "Hiragana" },
    { kana: "あね", kanji: "姉", romaji: "ane", translation: { en: "older sister", it: "sorella maggiore" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "あに", kanji: "兄", romaji: "ani", translation: { en: "older brother", it: "fratello maggiore" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "あめ", kanji: "雨", romaji: "ame", translation: { en: "rain", it: "pioggia" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "いえ", kanji: "家", romaji: "ie", translation: { en: "house, home", it: "casa" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "いぬ", kanji: "犬", romaji: "inu", translation: { en: "dog", it: "cane" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "いけ", kanji: "池", romaji: "ike", translation: { en: "pond", it: "stagno" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "いと", kanji: "糸", romaji: "ito", translation: { en: "thread", it: "filo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "うた", kanji: "歌", romaji: "uta", translation: { en: "song", it: "canzone" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "うみ", kanji: "海", romaji: "umi", translation: { en: "sea, ocean", it: "mare" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "うわさ", kanji: "噂", romaji: "uwasa", translation: { en: "rumor", it: "pettegolezzo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "おとこ", kanji: "男", romaji: "otoko", translation: { en: "man", it: "uomo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "おんな", kanji: "女", romaji: "onna", translation: { en: "woman", it: "donna" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "おそい", kanji: "遅い", romaji: "osoi", translation: { en: "slow, late", it: "lento, tardi" }, partOfSpeech: "adjective", type: "Hiragana" },
    { kana: "おいしい", kanji: "美味しい", romaji: "oishii", translation: { en: "delicious", it: "delizioso" }, partOfSpeech: "adjective", type: "Hiragana" },
    { kana: "おかね", kanji: "お金", romaji: "okane", translation: { en: "money", it: "soldi, denaro" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "おと", kanji: "音", romaji: "oto", translation: { en: "sound, noise", it: "suono, rumore" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "かね", kanji: "金", romaji: "kane", translation: { en: "money", it: "soldi, denaro" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "かみ", kanji: "紙", romaji: "kami", translation: { en: "paper, hair", it: "carta, capelli" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "かお", kanji: "顔", romaji: "kao", translation: { en: "face", it: "viso, faccia" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "かた", kanji: "肩", romaji: "kata", translation: { en: "shoulder", it: "spalla" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "からい", kanji: "辛い", romaji: "karai", translation: { en: "spicy", it: "piccante" }, partOfSpeech: "adjective", type: "Hiragana" },
    { kana: "かわ", kanji: "川", romaji: "kawa", translation: { en: "river", it: "fiume" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "きく", kanji: "聞く", romaji: "kiku", translation: { en: "to listen, hear", it: "ascoltare" }, partOfSpeech: "verb", type: "Hiragana" },
    { kana: "きた", kanji: "北", romaji: "kita", translation: { en: "north", it: "nord" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "きもの", kanji: "着物", romaji: "kimono", translation: { en: "kimono", it: "kimono" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "くも", kanji: "雲", romaji: "kumo", translation: { en: "cloud, spider", it: "nuvola, ragno" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "くるま", kanji: "車", romaji: "kuruma", translation: { en: "car, vehicle", it: "macchina, auto" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "くすり", kanji: "薬", romaji: "kusuri", translation: { en: "medicine", it: "medicina" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "くつ", kanji: "靴", romaji: "kutsu", translation: { en: "shoes", it: "scarpe" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "くち", kanji: "口", romaji: "kuchi", translation: { en: "mouth", it: "bocca" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "こえ", kanji: "声", romaji: "koe", translation: { en: "voice", it: "voce" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ここ", romaji: "koko", translation: { en: "here", it: "qui" }, partOfSpeech: "pronoun", type: "Hiragana" },
    { kana: "こころ", kanji: "心", romaji: "kokoro", translation: { en: "heart", it: "cuore" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "こと", kanji: "事", romaji: "koto", translation: { en: "thing, matter", it: "cosa, fatto" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "さくら", kanji: "桜", romaji: "sakura", translation: { en: "cherry blossom", it: "fiore di ciliegio" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "さけ", kanji: "酒", romaji: "sake", translation: { en: "sake, alcohol", it: "sake, alcol" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "さかな", kanji: "魚", romaji: "sakana", translation: { en: "fish", it: "pesce" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "さる", kanji: "猿", romaji: "saru", translation: { en: "monkey", it: "scimmia" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "しお", kanji: "塩", romaji: "shio", translation: { en: "salt", it: "sale" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "しか", kanji: "鹿", romaji: "shika", translation: { en: "deer", it: "cervo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "した", kanji: "下", romaji: "shita", translation: { en: "tongue, under", it: "lingua, sotto" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "しろい", kanji: "白い", romaji: "shiroi", translation: { en: "white", it: "bianco" }, partOfSpeech: "adjective", type: "Hiragana" },
    { kana: "すし", kanji: "寿司", romaji: "sushi", translation: { en: "sushi", it: "sushi" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "すいか", kanji: "西瓜", romaji: "suika", translation: { en: "watermelon", it: "anguria" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "すこし", kanji: "少し", romaji: "sukoshi", translation: { en: "a little", it: "un po'" }, partOfSpeech: "adverb", type: "Hiragana" },
    { kana: "せかい", kanji: "世界", romaji: "sekai", translation: { en: "world", it: "mondo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "そこ", romaji: "soko", translation: { en: "there", it: "lì" }, partOfSpeech: "pronoun", type: "Hiragana" },
    { kana: "そら", kanji: "空", romaji: "sora", translation: { en: "sky", it: "cielo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "そと", kanji: "外", romaji: "soto", translation: { en: "outside", it: "fuori" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "たこ", kanji: "蛸", romaji: "tako", translation: { en: "octopus", it: "polpo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "たかい", kanji: "高い", romaji: "takai", translation: { en: "high, expensive", it: "alto, costoso" }, partOfSpeech: "adjective", type: "Hiragana" },
    { kana: "つくえ", kanji: "机", romaji: "tsukue", translation: { en: "desk", it: "scrivania" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "つち", kanji: "土", romaji: "tsuchi", translation: { en: "soil, earth", it: "terra, suolo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "て", kanji: "手", romaji: "te", translation: { en: "hand", it: "mano" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "てんき", kanji: "天気", romaji: "tenki", translation: { en: "weather", it: "tempo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "とら", kanji: "虎", romaji: "tora", translation: { en: "tiger", it: "tigre" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "とり", kanji: "鳥", romaji: "tori", translation: { en: "bird", it: "uccello" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "とけい", kanji: "時計", romaji: "tokei", translation: { en: "clock, watch", it: "orologio" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "なつ", kanji: "夏", romaji: "natsu", translation: { en: "summer", it: "estate" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "なまえ", kanji: "名前", romaji: "namae", translation: { en: "name", it: "nome" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "なみ", kanji: "波", romaji: "nami", translation: { en: "wave", it: "onda" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "にし", kanji: "西", romaji: "nishi", translation: { en: "west", it: "ovest" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "にく", kanji: "肉", romaji: "niku", translation: { en: "meat", it: "carne" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ねこ", kanji: "猫", romaji: "neko", translation: { en: "cat", it: "gatto" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "のり", kanji: "海苔", romaji: "nori", translation: { en: "seaweed, glue", it: "alga nori, colla" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "のむ", kanji: "飲む", romaji: "nomu", translation: { en: "to drink", it: "bere" }, partOfSpeech: "verb", type: "Hiragana" },
    { kana: "はこ", kanji: "箱", romaji: "hako", translation: { en: "box", it: "scatola" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "はな", kanji: "花", romaji: "hana", translation: { en: "flower, nose", it: "fiore, naso" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "はし", kanji: "橋", romaji: "hashi", translation: { en: "chopsticks, bridge", it: "bacchette, ponte" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "はる", kanji: "春", romaji: "haru", translation: { en: "spring", it: "primavera" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ひと", kanji: "人", romaji: "hito", translation: { en: "person", it: "persona" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ひかり", kanji: "光", romaji: "hikari", translation: { en: "light", it: "luce" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ひこうき", kanji: "飛行機", romaji: "hikouki", translation: { en: "airplane", it: "aereo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ふね", kanji: "船", romaji: "fune", translation: { en: "ship, boat", it: "nave, barca" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ふゆ", kanji: "冬", romaji: "fuyu", translation: { en: "winter", it: "inverno" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "へや", kanji: "部屋", romaji: "heya", translation: { en: "room", it: "stanza" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ほし", kanji: "星", romaji: "hoshi", translation: { en: "star", it: "stella" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ほね", kanji: "骨", romaji: "hone", translation: { en: "bone", it: "osso" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "まち", kanji: "町", romaji: "machi", translation: { en: "town, city", it: "città, paese" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "まつ", kanji: "松", romaji: "matsu", translation: { en: "pine tree, to wait", it: "pino, aspettare" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "みみ", kanji: "耳", romaji: "mimi", translation: { en: "ear", it: "orecchio" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "みち", kanji: "道", romaji: "michi", translation: { en: "road, path", it: "strada" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "むし", kanji: "虫", romaji: "mushi", translation: { en: "insect", it: "insetto" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "むね", kanji: "胸", romaji: "mune", translation: { en: "chest", it: "petto" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "め", kanji: "目", romaji: "me", translation: { en: "eye", it: "occhio" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "もの", kanji: "物", romaji: "mono", translation: { en: "thing", it: "cosa" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "もり", kanji: "森", romaji: "mori", translation: { en: "forest", it: "foresta" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "やま", kanji: "山", romaji: "yama", translation: { en: "mountain", it: "montagna" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ゆき", kanji: "雪", romaji: "yuki", translation: { en: "snow", it: "neve" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ゆめ", kanji: "夢", romaji: "yume", translation: { en: "dream", it: "sogno" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "よる", kanji: "夜", romaji: "yoru", translation: { en: "night", it: "notte" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "よむ", kanji: "読む", romaji: "yomu", translation: { en: "to read", it: "leggere" }, partOfSpeech: "verb", type: "Hiragana" },
    { kana: "らく", kanji: "楽", romaji: "raku", translation: { en: "easy, comfortable", it: "comodo, facile" }, partOfSpeech: "adjective", type: "Hiragana" },
    { kana: "りす", romaji: "risu", translation: { en: "squirrel", it: "scoiattolo" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "れい", kanji: "零", romaji: "rei", translation: { en: "zero, bow", it: "zero, inchino" }, partOfSpeech: "noun", type: "Hiragana" },
    { kana: "ろく", kanji: "六", romaji: "roku", translation: { en: "six", it: "sei" }, partOfSpeech: "number", type: "Hiragana" },
    { kana: "わたし", kanji: "私", romaji: "watashi", translation: { en: "I, me", it: "io, me" }, partOfSpeech: "pronoun", type: "Hiragana" },
    { kana: "わに", romaji: "wani", translation: { en: "crocodile", it: "coccodrillo" }, partOfSpeech: "noun", type: "Hiragana" },

    // --- KATAKANA WORDS ---
    { kana: "カメラ", romaji: "kamera", translation: { en: "camera", it: "fotocamera" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "アメリカ", romaji: "amerika", translation: { en: "America", it: "America" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "サクラ", romaji: "sakura", translation: { en: "cherry blossom", it: "fiore di ciliegio" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "イカ", romaji: "ika", translation: { en: "squid", it: "seppia, calamaro" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "マイク", romaji: "maiku", translation: { en: "microphone", it: "microfono" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "テスト", romaji: "tesuto", translation: { en: "test, exam", it: "test, verifica" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "トイレ", romaji: "toire", translation: { en: "toilet, restroom", it: "bagno, gabinetto" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ココア", romaji: "kokoa", translation: { en: "cocoa", it: "cacao" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ナイフ", romaji: "naifu", translation: { en: "knife", it: "coltello" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "クラス", romaji: "kurasu", translation: { en: "class, classroom", it: "classe" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "テキスト", romaji: "tekisuto", translation: { en: "textbook", it: "libro di testo, testo" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ホテル", romaji: "hoteru", translation: { en: "hotel", it: "hotel, albergo" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ヘリ", romaji: "heri", translation: { en: "helicopter", it: "elicottero" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ヒント", romaji: "hinto", translation: { en: "hint, clue", it: "indizio, suggerimento" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "インク", romaji: "inku", translation: { en: "ink", it: "inchiostro" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ミント", romaji: "minto", translation: { en: "mint", it: "menta" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ハサミ", romaji: "hasami", translation: { en: "scissors", it: "forbici" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "メモ", romaji: "memo", translation: { en: "memo, note", it: "promemoria" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ネクタイ", romaji: "nekutai", translation: { en: "necktie", it: "cravatta" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "アニメ", romaji: "anime", translation: { en: "anime", it: "anime, cartone animato" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "スマホ", romaji: "sumaho", translation: { en: "smartphone", it: "smartphone" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "オアシス", romaji: "oashisu", translation: { en: "oasis", it: "oasi" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ロシア", romaji: "roshia", translation: { en: "Russia", it: "Russia" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "イタリア", romaji: "itaria", translation: { en: "Italy", it: "Italia" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ライフ", romaji: "raifu", translation: { en: "life", it: "vita" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ドア", romaji: "doa", translation: { en: "door", it: "porta" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ウニ", romaji: "uni", translation: { en: "sea urchin", it: "riccio di mare" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "コメ", romaji: "kome", translation: { en: "rice", it: "riso" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ライス", romaji: "raisu", translation: { en: "rice", it: "riso" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ラム", romaji: "ramu", translation: { en: "lamb, rum", it: "agnello, rum" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "フランス", romaji: "furansu", translation: { en: "France", it: "Francia" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "アフリカ", romaji: "afurika", translation: { en: "Africa", it: "Africa" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "イラク", romaji: "iraku", translation: { en: "Iraq", it: "Iraq" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "ヘキサ", romaji: "hekisa", translation: { en: "hex", it: "esa" }, partOfSpeech: "noun", type: "Katakana" },
    { kana: "キロ", romaji: "kiro", translation: { en: "kilo", it: "chilo" }, partOfSpeech: "noun", type: "Katakana" }
];
